<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>HonestFlow.WpfPrototype</AssemblyName>
    <RootNamespace>HonestFlow.WpfPrototype</RootNamespace>
    <ApplicationIcon>..\Resourses\hf.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
